# Семинар 01 - Первичный анализ данных, профайлинг, векторизация, пайплайны

In [4]:
# TODO: Содержание

<a id="0"></a>
# 0 Intro

## 0.0. Keeping a fork up to date

### 0. Нажмите кнопку fork в правом верънем углу интерфейса

### 1. Клонируйте репозиторий к себе на локальную машину:

> `git clone https://github.com/YOUR-USERNAME/ml_mipt_dafe.git`

### 2. Свяжите вашу копию с оригинальным репозиторием:
> `cd into/cloned/fork-repo`

> `git remote add upstream https://github.com/ml-dafe/ml_mipt_dafe.git`

> `git fetch upstream`

Про то, зачем мы делаем иммено так подробнее можно почитать [тут](https://git-scm.com/book/ru/v2/Ветвление-в-Git-Удалённые-ветки).
### 3. Обновите ваш репозиторий, чтобы загрузить изменения оригинального репозитория:
> `git pull upstream master`
### 4. После внесения изменения в проект на локальной машине обновите свой репозиторий:
> `git add *` - загрузить все изменения

> `git commit -m "comment"` - сделать локальный коммит

> `git push origin main` - загрузить локальный коммит в репозиторий

! Не забудьте про файлик .gitignore, чтобы не загружать лишнего. Подробнее про него читаем [тут](https://wiki.merionet.ru/articles/fajl-gitignore-kak-ignorirovat-fajly-i-papki-v-git).


## 0.1. Создание окружения

### Вариант max:

 [Ubuntu](https://help.ubuntu.ru/wiki/%D0%BF%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4%D0%B8%D0%BC_%D0%BD%D0%B0_ubuntu-linux_-_%D0%B8%D0%BD%D1%81%D1%82p%D1%83%D0%BA%D1%86%D0%B8%D1%8F_%D0%B4%D0%BB%D1%8F_%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F_windows)

[Drivers](https://linuxconfig.org/how-to-install-the-nvidia-drivers-on-ubuntu-18-04-bionic-beaver-linux)

[CUDA+CUDNN](https://medium.com/@sh.tsang/tutorial-cuda-v10-2-cudnn-v7-6-5-installation-ubuntu-18-04-3d24c157473f)

[CUDA alternative](https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal) (Можно также использовать этот шаг для Windows)

[CUDA GUIDE](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html)

Anaconda + pycharm (студентам бесплатно про версия)

### Вариант min:

Anaconda
> `conda update conda`

> `conda create -n ml_env python=3.7`

> `conda activate ml_env`

> `conda install -n ml_env numpy`

> `conda list`

> `pip freeze`

> `conda env list`

> `conda deactivate`

> `conda env remove -n ml_env`

### Вариант poor:

Google drive -> загрузить файл -> открыть с помощью -> Google colaboratory

In [5]:
from google.colab import drive
drive.mount('/content/gdrive/')

ModuleNotFoundError: No module named 'google'

In [ ]:
!ls ./gdrive/My\ Drive/Colab\ Notebooks

## 0.2. Jupyter notebook

### 0.2.1. Markdown
[Здесь](https://athena.brynmawr.edu/jupyter/hub/dblank/public/Jupyter%20Notebook%20Users%20Manual.ipynb) представлено подробное руководство по Markdown, широко используемое в jupyter, github и т. д. Вкратце, это позволяет:

0. Делать списки
1. 
## Делать
### заголовки
#### разных
##### масштабов
3. писать *текст* <s>самыми</s> **разными** способами
4. добавлять [гиперссылки](http://imgs.xkcd.com/comics/the_universal_label.png)


* Делать ненумерованные списки
    * в 
    * том
        * числе
            * и
                * вложенные

<img src=data/lena.jpg> картиночки</img>

использовать Markdown:
    
$
\left\{
\begin{array}{ll}
x = 16 \sin^3 (t) \\ 
y = 13 \cos (t) - 5 \cos (2t) - 2 \cos (3t) - \cos (4t) \\
t \in [0, 2 \pi]
\end{array}
\right.$

а также писать такие символы как $\pi$ внутри строки.

### 0.2.2. Горячие клавиши

Использование горячих клавиш позволяет очень cильно облегчить и ускорить работу с любой программой, особенно связанной со вводом текста. В плане горячих клавиш очень продвинутым является текстовый редактор vim. В нем существует отдельный режим, мозволяющий пользоваться горячими клавишами. В Jupyter notebook поддерживается та же концепция.

Существуют 2 режима работы: режим ввода и командный режим. Режим ввода отображается зеленой рамкой вокруг активной ячейки, командный режим -- синей. Для того, чтобы переключиться из режима ввода в командный режим необходимо нажать `Esc`, переход в режим редактирования осуществляется по нажатию клавиши `Enter`.

**В командном режиме часто используются следующие горячие клавиши:**
* `b` -- вставить пустую ячейку после текущей
* `a` -- вставить пустую ячейку перед текучей
-----
* `c` -- копировать текущую ячейку
* `x` -- вырезать ячейку
* `v` -- вставить ячейку из буфера после текущей
-----
* `dd` -- удалить текущую ячейку
* `z` -- отменить предыдущее действие (в юпитере не последней версии можно отменить ТОЛЬКО ОДНО действие) 
-----
* `m` -- перевести ячейку в режим Markdown
* `y` -- перевести ячейку в режим кода
* `l` -- отображать номера строк
* `o` -- скрыть/показать вывод текущей ячейки
-----
* `ii` -- остановить выполнение текущей ячейки
* `00` -- перезагрузить ядро
* `s` -- сохранить notebook
-----
* `h` -- Показать справку по горячим клавишам

**Некоторые сочетания используются в режиме редактирования:**
* `Tab` (в  начале строки либо для выделенных строк) -- добавить отступ
* `Shift+Tab` (в  начале строки либо для выделенных строк) -- убрать отступ
-----
* `Tab` -- автодополнение вводимой команды
* `Shift+Tab` -- показать docstring введеннной команды
-----
* `Clrl+/` -- закомментировать выделеные строки

-----
* `Shift+Enter` -- выполнить текущую ячейку кода и перейти к следующей
* `Ctrl+Enter` -- выполнить текущую ячейку кода и остаться на ней
* `Alt+Enter` -- выполнить текущую ячейку кода и создать новую

Также Jupytr Notebook имеет большое количество встроенных "магических" функций. С некоторыми познакомимся в этом курсе, про другие стоит рассказать сразу.

In [ ]:
%lsmagic

Выполнение bat/bash комманд (могут быть проблемы с кодировкой на Windows):

In [ ]:
ls

### 0.2.3. Замер времени выполнения кода

Измерение времени выполнения ячейки кода:

In [6]:
import math

In [7]:
%%time
a = 352e+11
for i in range(10000):
    a = math.sin(a)

CPU times: total: 0 ns
Wall time: 997 µs


Время выполнения конкретной строки из блока

In [8]:
%time a = 352e+10
for i in range(10000):
    a = math.sin(a)

CPU times: total: 0 ns
Wall time: 0 ns


Замер времени выполнения в цикле

In [9]:
%timeit a = 352e+10
for i in range(10000):
    a = math.sin(a)

12.9 ns ± 0.274 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


<a id="1"></a>
# 1 NumPy

**NumPy** — великолепная библиотека Python для матричных вычислений. Он позволяет [легко] работать с матрицами, массивами, математикой и т.п. Кроме того, она позволяет (и поощряет) векторные операции, которые **гораздо** быстрее.

 - [numpy](http://www.numpy.org)
 - [numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/)
 - [100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/)

In [10]:
# show several prints in one cell. This will allow us to condence every trick in one cell.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## 1.0. Вводная часть

In [11]:
import numpy as np

### 1.0.0. Размерность

Основной тип  — [numpy.ndarray](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.array.html). 
Каждый `ndarray` имеет оси.  
<img src=data/numpy_array_axes.png></img>

In [15]:
vec = np.array([1, 2, 3])
vec.ndim  # количество осей
vec.shape  # размерность массива

1

(3,)

In [16]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.ndim  # количество осей
mat.shape  # размерность массива

2

(2, 3)

### 1.0.1. Типы данных

В Numpy есть разные встроенные типы данных, с которыми мы будем встречаться, аналогичные C++.  
<br>
<img src=data/numpy_dtypes.png></img>

In [47]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.dtype  # Тип данных в массиве
mat.nbytes  # Занимаемое в памяти место 
mat

dtype('int32')

24

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
mat = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)  # Явно указываем тип данных в массиве
mat.dtype  # Тип данных в массиве
mat.nbytes  # Занимаемое в памяти место 
mat

dtype('float64')

48

array([[1., 2., 3.],
       [4., 5., 6.]])

### 1.0.2 Создание векторов и матриц 

In [20]:
np.zeros((3,))  # Создание матрицы из нулей 
np.zeros((3,), dtype=bool)
np.zeros((3,), dtype=np.longfloat)

array([0., 0., 0.])

array([False, False, False])

array([0., 0., 0.], dtype=float64)

In [23]:
np.ones((3, 4))  # Создание матрицы из единиц

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.identity(3)  # Создание единичной матрицы

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.arange(2, 20, 3)  # Создание вектора с указанием границ и шага (как range)
np.linspace(1, 10, 4)  # Создание вектора с указанием границ и количества значений между ними (границы включительно)

array([ 2,  5,  8, 11, 14, 17])

array([ 1.,  4.,  7., 10.])

### 1.0.3. Изменение формы массива**  

Изменение формы происходит при помощи функции _np.reshape_
<br>
<img src=data/numpy_reshape.png> </img>

In [39]:
A = np.linspace(1, 6, 6)
A
A.reshape(2, 3)  # Изменение формы 

array([1., 2., 3., 4., 5., 6.])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
C = A.reshape(3, -1)  # Автоматический подбор размеров матрицы
C

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

Или при помощи транспонирования

In [41]:
C.T  
C.transpose()

array([[1., 3., 5.],
       [2., 4., 6.]])

array([[1., 3., 5.],
       [2., 4., 6.]])

## 1.1. Базовые операции над массивами

### 1.1.0. Операции с массивами одинаковой размерности

Сложение, умножение и другие математические операции производятся поэлементно:
$$c_i = a_i + b_i$$

In [57]:
A = np.arange(9).reshape(3, 3)
B = np.arange(8, 17).reshape(3, 3)
A
B

C = A + B
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

array([[ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [62]:
A = np.arange(9).reshape(3, 3)
B = np.arange(8, 17).reshape(3, 3)
A
B
A * B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

array([[  0,   9,  20],
       [ 33,  48,  65],
       [ 84, 105, 128]])

### 1.1.1 Операции с разными размерностями

По возможности происходит так, как показано на картинке.
<img src=data/numpy_adding.jpg> </img>

In [64]:
A = np.arange(0, 31, 10).reshape(-1, 1)
B = np.arange(1, 4)
A
B
A + B

array([[ 0],
       [10],
       [20],
       [30]])

array([1, 2, 3])

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [63]:
A = np.arange(9).reshape(3, 3)
A
A + 5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [59]:
D = np.arange(9, dtype=np.int8).reshape(3, 3)
D
D * 2
D * 20

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int8)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]], dtype=int8)

array([[   0,   20,   40],
       [  60,   80,  100],
       [ 120, -116,  -96]], dtype=int8)

In [69]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 4)
A
B
A + B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

### 1.1.2. Матричное умножение

In [70]:
A = np.arange(9).reshape(3, 3)
B = np.arange(8, 17).reshape(3, 3)
A
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [71]:
A.dot(B)
A@B

array([[ 39,  42,  45],
       [138, 150, 162],
       [237, 258, 279]])

array([[ 39,  42,  45],
       [138, 150, 162],
       [237, 258, 279]])

### 1.1.3 Индексирование

In [76]:
A = np.arange(9).reshape(3, 3)
A[:]
A[:, 1]
A[:, 1:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([1, 4, 7])

array([[1, 2],
       [4, 5],
       [7, 8]])

In [77]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [78]:
A[:, 2:6]

array([[ 2,  3,  4,  5],
       [11, 12, 13, 14],
       [20, 21, 22, 23],
       [29, 30, 31, 32],
       [38, 39, 40, 41],
       [47, 48, 49, 50],
       [56, 57, 58, 59],
       [65, 66, 67, 68],
       [74, 75, 76, 77]])

In [79]:
A[:, 2:6:3] 

array([[ 2,  5],
       [11, 14],
       [20, 23],
       [29, 32],
       [38, 41],
       [47, 50],
       [56, 59],
       [65, 68],
       [74, 77]])

In [80]:
# Маски
A % 3
A % 3 == 0
A[A % 3 == 0]

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]], dtype=int32)

array([[ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False]])

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78])

### 1.1.4. Остальное

Рассматриваем остальные приятные возможности, такие как:
- минимум
- максимум
- сумма
- среднее
- стд
- поэлементые математические операции

In [72]:
A = np.arange(9).reshape(3, 3)
B = np.arange(8, 17).reshape(3, 3)
D = A@B
D
D.max(axis=1)
D.min(axis=0)

array([[ 39,  42,  45],
       [138, 150, 162],
       [237, 258, 279]])

array([ 45, 162, 279])

array([39, 42, 45])

In [73]:
D.sum()
D.sum(axis=0)
np.sum(D, axis=0)

1350

array([414, 450, 486])

array([414, 450, 486])

In [74]:
D.mean()
D.std()

150.0

88.92693630166283

In [75]:
A = np.arange(9).reshape(3, 3)
A
np.sin(A)
np.log(A)
np.exp2(A)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

C:\Users\kitro\AppData\Local\Temp\ipykernel_9976\2077385271.py:4: RuntimeWarning: divide by zero encountered in log
  np.log(A)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154]])

array([[  1.,   2.,   4.],
       [  8.,  16.,  32.],
       [ 64., 128., 256.]])

## 1.2. Векторизация


### 1.2.0. Математические операции с массивами

In [ ]:
n = 100_000_000
l = list(range(n))

In [ ]:
%timeit for i in range(n): l[i] += 17

In [ ]:
%%time

%time arr = np.array(l)
%time arr += 17

<a id = "2"></a>
# 2. Pandas

In [ ]:
# basic libraries
import os
import numpy as np
import pandas as pd

# show several prints in one cell. This will allow us to condence every trick in one cell.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
# this will allow us to print all the files as we generate more in the kernel
def print_files():
    for dirname, _, filenames in os.walk('datasets'):
        for filename in filenames:
            print(os.path.join(dirname, filename))

# check Trick 91 for an example
def generate_sample_data(): # creates a fake df for testing
    number_or_rows = 20
    num_cols = 7
    cols = list("ABCDEFG")
    df = pd.DataFrame(np.random.randint(1, 20, size = (number_or_rows, num_cols)), columns=cols)
    df.index = pd.util.testing.makeIntIndex(number_or_rows)
    return df

# check Trick 91 for an example
def generate_sample_data_datetime(): # creates a fake df for testing
    number_or_rows = 365*24
    num_cols = 2
    cols = ["sales", "customers"]
    df = pd.DataFrame(np.random.randint(1, 20, size = (number_or_rows, num_cols)), columns=cols)
    df.index = pd.util.testing.makeDateIndex(number_or_rows, freq="H")
    return df


print_files()

In [ ]:
df = pd.read_csv(r"C:\Users\kitro\JupiterProjects\ML\datasets\US_Accidents_March23.csv")
print("The shape of the df is {}".format(df.shape))

del df

df = pd.read_csv(r"C:\Users\kitro\JupiterProjects\ML\datasets\US_Accidents_March23.csv", skiprows = lambda x: x>0 and np.random.rand() > 0.01)
print("The shape of the df is {}. It has been reduced 100 times!".format(df.shape))


'''
How it works:
skiprows accepts a function that is evaluated against the integer index.
x > 0 makes sure that the headers is not skipped
np.random.rand() > 0.01 returns True 99% of the tie, thus skipping 99% of the time.
Note that we are using skiprows
'''

In [ ]:
df